version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "foo:1:1,bar:1:1,baz:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  svc1:
    image: spring-docker-kafka/svc1:latest
    ports:
      - "8080:8080"
  svc2:
      image: spring-docker-kafka/svc2:latest
      ports:
        - "8081:8080"
